# This is the single source of truth for your build settings.
# It will override the settings in the Netlify UI.

[build]
  # 1. Base directory: Where to run install commands.
  base = "frontend"
  
  # 2. Build command: The command to build your SvelteKit site.
  command = "npm run build"
  
  # 3. Publish directory: Where the finished site is located after build.
  publish = "frontend/build"
  
  # 4. Functions directory: Where your Python backend functions are.
  functions = "netlify/functions"

# This sets the timeout for all functions.
[functions."*"]
  timeout = 120