# This is the single source of truth for your build.

[build]
  # 1. Base directory: Where Netlify runs install & build commands.
  # This correctly points to your SvelteKit project.
  base = "frontend"
  
  # 2. Build command: The standard command to build your SvelteKit site.
  command = "npm run build"
  
  # 3. Publish directory: Where the finished site is, relative to the 'base' directory.
  publish = "build"
  
  # 4. Functions directory: Where your Python backend functions are.
  functions = "netlify/functions"

# This sets the timeout for all functions.
[functions."*"]
  timeout = 120